# Generated by Django 4.0.10 on 2026-08-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('painting_name', models.CharField(max_length=400)),
                ('year_drawn', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('width', models.DecimalField(decimal_places=1, max_digits=3)),
                ('height', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
    ]
