# Generated by Django 4.0.10 on 2026-08-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='painting',
            name='summary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='painting',
            name='height',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='painting',
            name='image',
            field=models.ImageField(upload_to='paintings/'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='painting_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='painting',
            name='width',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='painting',
            name='year_drawn',
            field=models.CharField(max_length=6),
        ),
    ]
