# Generated by Django 4.0.10 on 2026-08-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0002_painting_price_painting_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='painting',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='painting',
            name='year_drawn',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
